CREATE DATABASE [TodoList];

/****** Object:  Table [dbo].[Todo]    Script Date: 19/07/2022 9:47:25 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TodoList].[dbo].[Todo](
	[Id] [uniqueidentifier] NOT NULL,
	[Title] [varchar](50) NULL,
	[Detail] [varchar](500) NULL,
	[Status] [bit] NULL,
 CONSTRAINT [PK_Todo] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO